###

GET http://localhost:3000

###

GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner":"Yahli",
    "title":"this is the title of the post",
    "content": "content of the post"
}

###

GET http://localhost:3000/posts/post/6745e1e408aba85a5302eee1

### 

GET http://localhost:3000/posts/post?sender=Inbal

###

PUT http://localhost:3000/posts
Content-Type: application/json

{
    "_id":"6745e1e408aba85a5302eee1",
    "owner":"Inbal",
    "title":"updated title",
    "content": "updated content"
}

############## Comments #################

POST http://localhost:3000/comments
Content-Type: application/json

{
    "owner":"Yahli",
    "content": "content of the comment",
    "postId": "6745e761b4250208fbf499b1"
}

###

GET http://localhost:3000/comments/6745e775b4250208fbf499b5


###

GET http://localhost:3000/comments/post/6745e761b4250208fbf499b1

### 

DELETE http://localhost:3000/comments/6745e5ac93ace2b2cce449c9

###

PUT http://localhost:3000/comments
Content-Type: application/json

{
    "_id":"6745e775b4250208fbf499b5",
    "content": "updated content"
}

############## Auth #################

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "bla",
    "email":"bla@user.com",
    "password": "123456"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"bla@user.com",
    "password": "123456"
}

###

POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdkMDFkNDE1ZmU5ZGYwMzQ5Zjk1MTgiLCJyYW5kb20iOiIwLjczNDA1MzU2NjQ2NjY5NDMiLCJpYXQiOjE3MzYyNDU3MzEsImV4cCI6MTczNjg1MDUzMX0.QNAox8oaaYfh987CQibhR3wTht8P-Gag1A1G96ijCrY"
}

###

POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzdkMDFkNDE1ZmU5ZGYwMzQ5Zjk1MTgiLCJyYW5kb20iOiIwLjYyMDQzNjYxMTc2Njk5OTciLCJpYXQiOjE3MzYyNDU5MTQsImV4cCI6MTczNjg1MDcxNH0.u3hS0xTuYT1JpUyAz8XI1gJGMTTz426-wlrYAxeSZJ0"
}

###





############## Users #################

GET http://localhost:3000/users/6770313c4f4286c25a9cd009


###

GET http://localhost:3000/users/

### 

DELETE http://localhost:3000/users/6770308debb71e5ebc511ab3

###

PUT http://localhost:3000/users
Content-Type: application/json

{
    "_id":"6770308debb71e5ebc511ab3",
    "email": "updated email"
}